server:
  port: ${SERVER_PORT:8080}

spring:
  data:
    redis:
      host: ${REDIS_HOST:192.168.88.42}
      port: ${REDIS_PORT:30379}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD:password}
      timeout: 60000